# -*- mode: ruby -*-
# vi: set ft=ruby :
nombreVM="Hadoop" #Nombre de la maquina
Vagrant.configure("2") do |config|
  config.vm.define "ansible" do |ansible|
    ansible.vm.box_check_update = false
    ansible.vm.network "forwarded_port", guest: 9870, host: 9870 #Puertos
    ansible.vm.network "forwarded_port", guest: 8088, host: 8088
    ansible.vm.box = "ubuntu/jammy64" #SO a utilizar
    ansible.vm.hostname = nombreVM  
    ansible.vm.provider "virtualbox" do |v| # Proveedor y configuración de hardware
      v.name = nombreVM
      v.memory = 8192
      v.cpus = 4
    end
    ansible.vm.synced_folder "config", "/config"
    ansible.vm.provision "shell", inline: <<-SHELL
      apt update
      apt install python3 python3-pip -y
      pip install ansible
      echo 'localhost' > /etc/ansible/hosts
      mkdir -p /root/.ssh
      ssh-keygen -t rsa -b 2048 -f /root/.ssh/id_rsa -N ""
      cat /root/.ssh/id_rsa.pub >> /root/.ssh/authorized_keys
      chmod 600 /root/.ssh/authorized_keys
      mkdir /ansiblecfg
      SHELL
    ansible.vm.provision "shell", run: "always", inline: <<-SHELL
      cp /config/* /ansiblecfg
      cd /ansiblecfg
      ansible-playbook playbook1-hadoop.yml
      SHELL
  end
end
